plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.zaturikakaomap'
version = '0.1.0'

android {
  namespace "expo.modules.zaturikakaomap"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
  }
  lintOptions {
    abortOnError false
  }
}

repositories {
  maven { url "https://devrepo.kakao.com/nexus/repository/kakaomap-releases/" }
}

dependencies {
  implementation "com.kakao.maps.open:android:2.13.2"
}
